# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Agq6nJMp2n9EGZnlqsxEy_kw6QwUva0v
"""

def kitob(belgi):
  if belgi=="Roman":
    return "Ikki eshik orasi"
  elif belgi=="Psixologik":
    return "Deyl Karnegi"
  elif belgi=="Sarguzasht":
    return "Shum bola"
  else:
    return "Kutubxonaga murojaat qiling "
belgi=input("Kitob nomini kiriting")
natija=kitob(belgi)
print(natija)