# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MXWH2giqF_S2Rz7Ql6Xs1XQyRUJhJQH0
"""

import pandas as pd

taxlil=pd.read_csv("/content/youtubers_df (1).csv")
print(taxlil)

taxlil=pd.read_csv("/content/youtubers_df (1).csv")
india_kanallar = taxlil[taxlil['Country'] == 'India']
print("Hindiston kanallari ro'yxati:")
display(india_kanallar.head())